<html>
<head>
   <title>HomeWater Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Data Deposit</h1>

<p><a href="/deposit/new">Add new deposit</a></p>
<?php
if(count($deposit) > 0):
?>
<table class="pure-table">
    <tr>
        <th>ID</th>
		<th>ID Depot</th>
        <th>Owner</th>
        <th>Waktu</th>
		<th>Nilai</th>
		<th>Aksi</th>
    </tr>
<?php
    $odd = true;
    foreach($deposit as $deposit): ?>
        <tr <?=$odd ? "class=\"pure-table-odd\"" : ""; ?>>
        <td><?=$deposit->getID() ?></td>
		<td><?=$deposit->getDepot_id() ?></td>
        <td><?=$deposit->getOwner() ?></td>
		<td><?=$deposit->getWaktu() ?></td>
		<td><?=$deposit->getNilai_deposit() ?></td>
		<td>
			<a href="<?=$router->pathFor('deposit-update', ['id' => $deposit->getId()])?>">Update</a>
			<a href="/deposit/<?=$deposit->getId()?>/delete">Delete</a>
        </td>
    </tr>

<?php 
    $odd = $odd ? false : true;
    endforeach; ?>
</table>
<?php else: ?>
<p>No current tickets</p>
<?php endif; ?>
<?php require 'footer.phtml' ?>
</body>
</html>

