<html>
<head>
    <title>Homewater Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Depot</h1>

<form class="pure-form" method="post" action="/depot/new">
    <label for="lonlat">Lonlat</label>
    <input name="lonlat" id="lonlat" type="text" size="60" /><br />
    <label for="owner">Owner</label>
    <input name="owner" id="owner" type="text" size="60" /><br />
    <label for="install_date">Tanggal Install</label>
    <input name="install_date" id="install_date" type="date" size="60" /><br />	
    <label for="saldo">Saldo</label>
    <input name="saldo" id="saldo" type="text" size="60" /><br />
    <input type="submit" class="pure-button" value="Create" />
</form>
<?php require 'footer.phtml' ?>
</body>
</html>


