<html>
<head>
    <title>HomeWater Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Update User</h1>
<form class="pure-form" method="post" action="/user/<?=$user->getUsername()?>/update">
	<label for="password">Password</label>
    <input name="password" 	   id="password"	 type="text" size="60"  value="<?=$user->getPassword()?>"/><br />
    <label for="nama">Nama</label>
    <input name="nm" 	   id="nm"	 type="text" size="60"  value="<?=$user->getNama()?>"/><br />
	<label for="usertype">Usertype</label>
    <input name="usertype" 	   id="usertype"	 type="text" size="60"  value="<?=$user->getUsertype()?>"/><br />
	<input name="usrnm" 	   id="usrnm"	 type="hidden" size="60"  value="<?=$user->getUsername()?>"/><br />
	<input type="submit" class="pure-button" value="Update" />
</form>
<?php require 'footer.phtml' ?>
</body>
</html>


